typography_spectrum: 0.47304
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2350127447862178
  lightness: 0.15360322897322476
  saturation: 0.3819822473451495
  rhythmicContrast: 0.020261448808014393
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93768
analytics:
  google: null
  facebook: null
  twitter: null
name: jeremyleavitt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: JSL
purpose: []
