name: jeremyleavitt
favicon: null
layout_spectrum: 0.75411
typography_spectrum: 0.48029
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2350127447862178
  lightness: 0.15360322897322476
  saturation: 0.3819822473451495
  rhythmicContrast: 0.020261448808014393
purpose: []
